version: "3"

services:
  app1:
    build: ./services/app1
    container_name: app1
    ports:
      - "5001:5001"
  app2:
    build: ./services/app2
    container_name: app2
    ports:
      - "5002:5002"